PARAMS = {  # 运行时参数
    "button_add_point": {'hyperType': 'point'},
    "button_add_rect": {'hyperType': 'rect'},
    "edit_text": {'hyperType': 'text', 'hyperConfig': {'nullable': False}},
    "edit_conf": {'hyperType': 'number', 'hyperDefault': 0.5},
    "edit_iou": {'hyperType': 'number', 'hyperDefault': 0.5},
    "toggle_preserve_existing_annotations": {'hyperType': 'check', 'hyperDefault': False},
    "button_reset_tracker": {'hyperType': 'check', 'hyperDefault': False},
}

CUSTOM_MODELS = [
        "segment_anything",
        "segment_anything_2",
        "segment_anything_2_video",
        "sam_med2d",
        "sam_hq",
        "yolov5",
        "yolov6",
        "yolov7",
        "yolov8",
        "yolov8_seg",
        "yolox",
        "yolov5_resnet",
        "yolov6_face",
        "rtdetr",
        "yolo_nas",
        "yolox_dwpose",
        "clrnet",
        "ppocr_v4",
        "yolov5_sam",
        "efficientvit_sam",
        "yolov5_track",
        "damo_yolo",
        "yolov8_sahi",
        "grounding_sam",
        "grounding_sam2",
        "grounding_dino",
        "yolov5_obb",
        "gold_yolo",
        "yolov8_efficientvit_sam",
        "ram",
        "yolov5_seg",
        "yolov5_ram",
        "yolov8_pose",
        "pulc_attribute",
        "internimage_cls",
        "edge_sam",
        "yolov5_cls",
        "yolov8_cls",
        "yolov8_obb",
        "yolov5_car_plate",
        "rtmdet_pose",
        "yolov9",
        "yolow",
        "yolov10",
        "rmbg",
        "depth_anything",
        "depth_anything_v2",
        "yolow_ram",
        "rtdetrv2",
        "yolov8_det_track",
        "yolov8_seg_track",
        "yolov8_obb_track",
        "yolov8_pose_track",
        "yolo11",
        "yolo11_cls",
        "yolo11_obb",
        "yolo11_seg",
        "yolo11_pose",
        "yolo11_det_track",
        "yolo11_seg_track",
        "yolo11_obb_track",
        "yolo11_pose_track",
    ]

marks_model_list = [
    "segment_anything",
    "segment_anything_2",
    "segment_anything_2_video",
    "sam_med2d",
    "sam_hq",
    "yolov5_sam",
    "efficientvit_sam",
    "yolov8_efficientvit_sam",
    "grounding_sam",
    "grounding_sam2",
    "edge_sam",
]

reset_tracker_model_list = [
    "yolov5_det_track",
    "yolov8_det_track",
    "yolov8_obb_track",
    "yolov8_seg_track",
    "yolov8_pose_track",
    "segment_anything_2_video",
    "yolo11_det_track",
    "yolo11_seg_track",
    "yolo11_obb_track",
    "yolo11_pose_track",
]

conf_model_list = [
    "damo_yolo",
    "gold_yolo",
    "grounding_dino",
    "rtdetr",
    "rtdetrv2",
    "yolo_nas",
    "yolov5_obb",
    "yolov5_seg",
    "yolov5_det_track",
    "yolov5",
    "yolov6",
    "yolov6_face",
    "yolov7",
    "yolov8_obb",
    "yolov8_pose",
    "yolov8_seg",
    "yolov8_det_track",
    "yolov8_seg_track",
    "yolov8_obb_track",
    "yolov8_pose_track",
    "yolov8",
    "yolov9",
    "yolov10",
    "yolo11",
    "yolo11_obb",
    "yolo11_seg",
    "yolo11_pose",
    "yolo11_det_track",
    "yolo11_seg_track",
    "yolo11_obb_track",
    "yolo11_pose_track",
    "yolow",
    "yolox",
]

iou_model_list = [
    "damo_yolo",
    "gold_yolo",
    "yolo_nas",
    "yolov5_obb",
    "yolov5_seg",
    "yolov5_det_track",
    "yolov5",
    "yolov6",
    "yolov7",
    "yolov8_obb",
    "yolov8_pose",
    "yolov8_seg",
    "yolov8_det_track",
    "yolov8_seg_track",
    "yolov8_obb_track",
    "yolov8_pose_track",
    "yolov8",
    "yolov9",
    "yolo11",
    "yolo11_obb",
    "yolo11_seg",
    "yolo11_pose",
    "yolo11_det_track",
    "yolo11_seg_track",
    "yolo11_obb_track",
    "yolo11_pose_track",
    "yolox",
]

preserve_existing_annotations_state_model_list = [
    "damo_yolo",
    "gold_yolo",
    "grounding_dino",
    "rtdetr",
    "rtdetrv2",
    "yolo_nas",
    "yolov5_obb",
    "yolov5_seg",
    "yolov5_det_track",
    "yolov5",
    "yolov6",
    "yolov7",
    "yolov8_obb",
    "yolov8_pose",
    "yolov8_seg",
    "yolov8_det_track",
    "yolov8_seg_track",
    "yolov8_obb_track",
    "yolov8_pose_track",
    "yolov8",
    "yolov9",
    "yolov10",
    "yolo11",
    "yolo11_obb",
    "yolo11_seg",
    "yolo11_pose",
    "yolo11_det_track",
    "yolo11_seg_track",
    "yolo11_obb_track",
    "yolo11_pose_track",
    "yolow",
    "yolox",
]